name: CI/CD to update the devcontainers

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "35 3 * * 1"

jobs:
  containers:
    name: Build Devcontainer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - dart
          - flutter
    steps:
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./images/${{ matrix.image }}
          pull: true
          tags: skycoder42/devcontainers/${{ matrix.image }}:latest
          sbom: true
          provenance: true
          push: ${{ github.ref == 'refs/heads/main' }}
